final List<Map<String, dynamic>> jsonWorkExperiences = [
  {
    "company": "Kodepedia",
    "position": "Senior Flutter Developer",
    "duration": "02/2025 - Present",
    "location": "Cairo, Egypt",
    "description": "Currently building scalable Flutter applications for Kodepedia clients.",
    "responsibilities": [
      "Leading Flutter development for client projects",
      "Implementing clean architecture and CI/CD pipelines",
      "Collaborating with designers and backend teams",
    ],
    "technologies": ["Flutter", "Dart", "Firebase", "Getx", "REST APIs", "Google Maps", "Firebase Firestore", "Paymob", "Push Notifications"],
    "icon": "FontAwesomeIcons.codeBranch",
    "color": "#607D8B",
    "companyUrl": "",
    "employmentType": "Full-time",
  },
  {
    "company": "World Of Systems (WOSS)",
    "position": "Senior Flutter Developer",
    "duration": "09/2023 - 02/2025",
    "location": "Cairo, Egypt",
    "description": "Worked on enterprise Flutter applications for large-scale systems.",
    "responsibilities": ["Architected scalable Flutter solutions", "Integrated advanced native modules", "Collaborated with cross-functional teams"],
    "technologies": ["Flutter", "Dart", "Firebase", "REST APIs", " Google Maps", "Push Notifications", "Geolocation", "Payment Gateway Integration"],
    "icon": "FontAwesomeIcons.layerGroup",
    "color": "#795548",
    "companyUrl": "",
    "employmentType": "Full-time",
  },
  {
    "company": "Fabrica Creative Studio",
    "position": "Senior Flutter Developer",
    "duration": "05/2022 - 09/2023",
    "location": "Cairo, Egypt",
    "description": "Led Flutter projects for creative mobile app solutions.",
    "responsibilities": [
      "Led development of multiple Flutter applications",
      "Mentored junior developers and reviewed code",
      "Optimized performance and implemented state management",
    ],
    "technologies": ["Flutter", "Dart", "Bloc", "Provider", "Firebase"],
    "icon": "FontAwesomeIcons.paintBrush",
    "color": "#E91E63",
    "companyUrl": "",
    "employmentType": "Full-time",
  },
  {
    "company": "Theqqa",
    "position": "Flutter Developer",
    "duration": "09/2021 - 05/2022",
    "location": "Egypt",
    "description": "Developed mobile solutions using Flutter for Theqqa platform.",
    "responsibilities": [
      "Developed cross-platform Flutter applications",
      "Integrated Firebase services and APIs",
      "Collaborated with designers for pixel-perfect UIs",
    ],
    "technologies": ["Flutter", "Dart", "Firebase", "REST APIs"],
    "icon": "FontAwesomeIcons.mobileAlt",
    "color": "#2196F3",
    "companyUrl": "",
    "employmentType": "Full-time",
  },
  {
    "company": "Freelancer",
    "position": "Android & Flutter Developer",
    "duration": "04/2020 - 09/2021",
    "location": "Remote",
    "description": "Delivered mobile applications using both Android native and Flutter cross-platform frameworks.",
    "responsibilities": [
      "Built cross-platform apps in Flutter for multiple clients",
      "Maintained native Android apps",
      "Managed full app lifecycle from development to publishing",
    ],
    "technologies": ["Flutter", "Dart", "Java", "Kotlin", "Firebase"],
    "icon": "FontAwesomeIcons.laptopCode",
    "color": "#FF9800",
    "companyUrl": "",
    "employmentType": "Freelance",
  },
  {
    "company": "ElWAHA",
    "position": "Android Developer",
    "duration": "10/2019 - 04/2020",
    "location": "Mansoura, Egypt",
    "description": "Worked on Android apps using Java and Kotlin with focus on scalability.",
    "responsibilities": [
      "Developed mobile apps with scalable architecture",
      "Implemented new features and bug fixes",
      "Collaborated with backend developers on API integration",
    ],
    "technologies": ["Java", "Kotlin", "Retrofit"],
    "icon": "FontAwesomeIcons.mobile",
    "color": "#9C27B0",
    "companyUrl": "",
    "employmentType": "Full-time",
  },
  {
    "company": "Hmaserv Company",
    "position": "Android Developer",
    "duration": "06/2018 - 10/2019",
    "location": "Alexandria, Egypt",
    "description": "Developed and maintained Android applications for business solutions.",
    "responsibilities": [
      "Created Android apps using Java and Kotlin",
      "Implemented clean architecture and reusable components",
      "Collaborated with QA team to ensure app stability",
    ],
    "technologies": ["Java", "Kotlin", "Room", "Retrofit"],
    "icon": "FontAwesomeIcons.building",
    "color": "#3F51B5",
    "companyUrl": "",
    "employmentType": "Full-time",
  },
  {
    "company": "Freelance",
    "position": "Android Developer",
    "duration": "2017 - 2018",
    "location": "Remote",
    "description": "Delivered Android apps for clients as a freelance developer.",
    "responsibilities": [
      "Developed and delivered custom Android applications",
      "Worked directly with clients to gather requirements",
      "Integrated REST APIs and optimized app performance",
    ],
    "technologies": ["Java", "Kotlin", "REST APIs"],
    "icon": "FontAwesomeIcons.code",
    "color": "#009688",
    "companyUrl": "",
    "employmentType": "Freelance",
  },
  {
    "company": "Self Learning",
    "position": "Android Developer",
    "duration": "2016 - 2017",
    "location": "Egypt",
    "description": "Self-taught Android development, building foundational skills in Java and Android SDK.",
    "responsibilities": [
      "Learned Android fundamentals through hands-on projects",
      "Built simple mobile apps using Java",
      "Explored UI design and layouts",
    ],
    "technologies": ["Java", "Android SDK"],
    "icon": "FontAwesomeIcons.android",
    "color": "#4CAF50",
    "companyUrl": "",
    "employmentType": "Self Learning",
  },
];
